### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Tobias-Keller** [baumerdev/bankdata-germany#5]
## Actual Behavior
Cant import the module in an angular  cli 16.2.4

error TS2307: Cannot find module 'bankdata-germany' or its corresponding type declarations.

**Comment by Tobias-Keller** [comment]
i think the problem exists last the latest update...yesterday i could build it

**Comment by baumerdev** [comment]
Please check if this problem is solved with version 1.2403.1
